# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev-intgrt',
                'doc_host': 'https://rbagdazian.github.io',
                'git_url': 'https://github.com/rbagdazian/nbdev-intgrt',
                'lib_path': 'nbdev_intgrt'},
  'syms': { 'nbdev_intgrt.core': {'nbdev_intgrt.core.foo': ('core.html#foo', 'nbdev_intgrt/core.py')},
            'nbdev_intgrt.intgrt': {'nbdev_intgrt.intgrt.intgrt': ('intgrt.html#intgrt', 'nbdev_intgrt/intgrt.py')}}}