# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['intgrt']

# %% ../00_core.ipynb 3
def intgrt(func, lbnd, ubnd, intvl):
    sumx =0
    lside=lbnd
    rside=lbnd+intvl
    while(rside<ubnd):
        avgval = (func(lside) + func(rside))/2
        dx = (rside-lside)
        sumx = sumx + (dx*avgval)
        lside = lside + intvl
        rside = rside + intvl
        #print(rside,ubnd)
    return sumx
